<a href="https://colab.research.google.com/github/Arif0000/Pytorch/blob/main/Pytorch_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is avail")
  print(f"using GPU {torch.cuda.get_device_name(0)}")
else:
  print('GPU not avail')

GPU is avail
using GPU Tesla T4


In [3]:
# Creating Tensor

In [4]:
torch.empty(2,3)
torch.zeros(2,3)
torch.ones(2,3)
torch.manual_seed(42)
torch.rand(2,3)
torch.tensor([12])

tensor([12])

In [5]:
# other ways

In [6]:
print("using arang ", torch.arange(0,10,2))

print("using linspace", torch.linspace(0,10,10))

print("using eye", torch.eye(5))

print("using full", torch.full((3,3),5))

using arang  tensor([0, 2, 4, 6, 8])
using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [7]:
# Tensor Shape

In [8]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)
print(x.shape)
print(torch.empty_like(x))
print(torch.zeros_like(x))
print(torch.ones_like(x))
print(torch.rand_like(x, dtype=torch.float32))


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([[         0, 1194016928,          0],
        [         0,          0,          0]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [9]:
# Tensor Data Type

In [10]:
print(x.dtype)
print(torch.tensor([1.0,2.0,3.0,4.0], dtype=torch.int32))
print(torch.tensor([1,2,3], dtype=torch.float32))
print(x.to(torch.float16))

torch.int64
tensor([1, 2, 3, 4], dtype=torch.int32)
tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)


In [11]:
# Mathematical operation

In [12]:
x = torch.rand(2,3)
print(x)
print( x + 2)
print( x - 2)
print( x  * 3)
print( x / 3)
print( (x * 100) // 3)
print((( x * 100) // 3) % 2)
print( x ** 2)


tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[2.8694, 2.5677, 2.7411],
        [2.4294, 2.8854, 2.5739]])
tensor([[-1.1306, -1.4323, -1.2589],
        [-1.5706, -1.1146, -1.4261]])
tensor([[2.6082, 1.7031, 2.2233],
        [1.2882, 2.6563, 1.7217]])
tensor([[0.2898, 0.1892, 0.2470],
        [0.1431, 0.2951, 0.1913]])
tensor([[28., 18., 24.],
        [14., 29., 19.]])
tensor([[0., 0., 0.],
        [0., 1., 1.]])
tensor([[0.7559, 0.3223, 0.5492],
        [0.1844, 0.7840, 0.3294]])


In [13]:
# Element Wise

In [14]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

print( a + b)
print( a - b)
print(a * b)
print( a / b)
print( a ** b)
print ( a % b)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])
tensor([[0.3719, 0.8969, 0.6284],
        [0.6407, 0.8441, 0.8378]])
tensor([[ 0.1613,  0.3580, -0.0892],
        [ 0.2420, -0.2503,  0.8255]])
tensor([[0.0281, 0.1691, 0.0967],
        [0.0880, 0.1625, 0.0051]])
tensor([[  2.5313,   2.3282,   0.7515],
        [  2.2139,   0.5426, 135.0043]])
tensor([[0.8700, 0.8820, 0.6248],
        [0.8495, 0.5146, 0.9989]])
tensor([[5.5950e-02, 8.8459e-02, 2.6963e-01],
        [4.2636e-02, 2.9692e-01, 2.6345e-05]])


In [15]:
c = torch.tensor([1,-2,3,-4])
print(torch.abs(c))
print(torch.neg(c))
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
print(torch.round(d))
print(torch.ceil(d))
print(torch.floor(d))
print(torch.clamp(d, min=2, max=3))

tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])
tensor([2., 2., 4., 4.])
tensor([2., 3., 4., 5.])
tensor([1., 2., 3., 4.])
tensor([2.0000, 2.3000, 3.0000, 3.0000])


In [16]:
# Reduction operation

In [17]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(torch.sum(e))
print(torch.sum(e, dim=0))
print(torch.sum(e,dim=1))
print(torch.mean(e))
print(torch.mean(e,dim=1))
print(torch.median(e))
print(torch.max(e))
print(torch.min(e))
print(torch.prod(e))
print(torch.std(e))
print(torch.var(e))
print(torch.argmax(e))
print(torch.argmin(e))

tensor(23.)
tensor([11.,  3.,  9.])
tensor([ 7., 16.])
tensor(3.8333)
tensor([2.3333, 5.3333])
tensor(3.)
tensor(9.)
tensor(0.)
tensor(0.)
tensor(3.0605)
tensor(9.3667)
tensor(3)
tensor(1)


In [18]:
# Matrix Operation

In [19]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)
print(torch.matmul(f,g))

tensor([[9, 6, 2],
        [0, 6, 2]])
tensor([[7, 9],
        [7, 3],
        [3, 4]])
tensor([[111, 107],
        [ 48,  26]])


In [20]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
print(torch.dot(vector1, vector2))
print(torch.transpose(f, 0, 1))

tensor(11)
tensor([[9, 0],
        [6, 6],
        [2, 2]])


In [21]:
h = torch.randint(size=(3,3), low =0, high=10 , dtype=torch.float32)
print(h)
print(torch.det(h))
print(torch.inverse(h))

tensor([[3., 7., 0.],
        [9., 0., 9.],
        [6., 9., 5.]])
tensor(-180.0000)
tensor([[ 0.4500,  0.1944, -0.3500],
        [-0.0500, -0.0833,  0.1500],
        [-0.4500, -0.0833,  0.3500]])


In [22]:
# Comparison operations

In [23]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)
print( i > j)
print( i < j)
print( i == j)
print( i != j)
print( i >= j)
print( i <= j)

tensor([[4, 8, 8],
        [6, 0, 0]])
tensor([[0, 0, 1],
        [3, 0, 1]])
tensor([[ True,  True,  True],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[False, False, False],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [ True, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [False,  True,  True]])


In [24]:
# Special Function

In [25]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(k)
print(torch.log(k))
print(torch.exp(k))
print(torch.sqrt(k))
print(torch.sigmoid(k))
print(torch.softmax(k, dim=0))
print(torch.relu(k))

tensor([[1., 7., 9.],
        [4., 3., 8.]])
tensor([[0.0000, 1.9459, 2.1972],
        [1.3863, 1.0986, 2.0794]])
tensor([[2.7183e+00, 1.0966e+03, 8.1031e+03],
        [5.4598e+01, 2.0086e+01, 2.9810e+03]])
tensor([[1.0000, 2.6458, 3.0000],
        [2.0000, 1.7321, 2.8284]])
tensor([[0.7311, 0.9991, 0.9999],
        [0.9820, 0.9526, 0.9997]])
tensor([[0.0474, 0.9820, 0.7311],
        [0.9526, 0.0180, 0.2689]])
tensor([[1., 7., 9.],
        [4., 3., 8.]])


In [26]:
# Inplace Operation

In [27]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)
print(m.add_(n))
print(torch.relu(m))

tensor([[0.1088, 0.1637, 0.7025],
        [0.6790, 0.9155, 0.2418]])
tensor([[0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860]])
tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])
tensor([[0.2680, 0.9289, 1.0004],
        [1.4825, 1.2968, 1.0278]])


In [28]:
# Tensor operation on GPU

In [30]:
torch.cuda.is_available()
device = torch.device('cuda')

torch.rand((2,3), device=device)

a = torch.rand(2,3)
print(a)

b = a.to(device)
print(b + 5)


tensor([[0.1115, 0.2477, 0.6524],
        [0.6057, 0.3725, 0.7980]])
tensor([[5.1115, 5.2477, 5.6524],
        [5.6057, 5.3725, 5.7980]], device='cuda:0')


In [31]:
import torch
import time
size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on cpu : { cpu_time:.4f} second")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on cpu : { gpu_time:.4f} second")

print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on cpu : 24.8939 second
Time on cpu : 0.1003 second

Speedup (CPU time / GPU time): 248.30840794777583


In [ ]:
# Reshaping Tensor

In [32]:
a = torch.ones(4,4)
print(a)
print(a.reshape(2,2,2,2))
print(a.flatten())

b= torch.rand(2,3,4)
print(b)
print(b.permute(2,1,0).shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [33]:
c = torch.rand(226,226,3)
print(c.unsqueeze(0).shape)

torch.Size([1, 226, 226, 3])


In [34]:
d = torch.rand(1,20)
print(d.squeeze(0).shape)

torch.Size([20])


In [ ]:
# Numpy and Pytorch

In [35]:
import numpy as np


In [36]:
a = torch.tensor([1,2,3])
print(a)
b = a.numpy()
print(type(b))

c = np.array([1,2,3])
print(c)

print(torch.from_numpy(c))

tensor([1, 2, 3])
<class 'numpy.ndarray'>
[1 2 3]
tensor([1, 2, 3])
